# Generated by Django 3.2.20 on 2023-12-22 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='cover_logo/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
